### ISSUE TITLE
Add ability to feature-flag which tests are expected to fail

### ISSUE THREAD

**Issue by di** [sigstore/sigstore-conformance#87]
**Description**

As raised in the clients repo today, individual clients which run the conformance suite action should have a way to declare which tests they expect to fail due to not supporting some feature.

Something like this:

```yaml
- uses: sigstore/sigstore-conformance@v0.0.5
  with:
    entrypoint: sigstore
    xfail:
      - some_test_name
      - some_other_test_name
```

Tests that are listed in the action configuration should still be run, but should be `xfail`'d (i.e., if they're expected to fail and they don't fail, the test suite should fail)

This should probably also handle changes to test names between action versions, by failing if a test is configured to xfail and it doesn't exist.
